# Change these first
owner: PuraVida-Technologies # Your GitHub organization or username, where this repository lives
repo: pura-vida-status # The name of this repository

sites:
  - name: Primary Site - Pura Vida Bitcoin
    url: https://puravidabitcoin.io/
  - name: Pay - Pura Vida Bitcoin
    url: https://pay.puravidabitcoin.io/
  - name: Wallet - Pura Vida Bitcoin
    url: https://wallet.puravidabitcoin.io/
  - name: Market - Pura Vida Bitcoin
    url: https://market.puravidabitcoin.io/
  - name: Admin Market - Pura Vida Bitcoin
    url: https://admin.market.puravidabitcoin.io/
  - name: Specter - Pura Vida Bitcoin
    url: https://specter.puravidabitcoin.io/
  - name: Admin - Pura Vida Bitcoin
    url: https://admin.puravidabitcoin.io/
  - name: ArgoCD - Pura Vida Bitcoin
    url: https://argocd.puravidabitcoin.io/
  - name: API Exchange Rates - Pura Vida Bitcoin
    url: https://api.puravidabitcoin.io/graphql
    method: POST
    headers:
      - "Authority: api.puravidabitcoin.io"
      - "Content-Type: application/json"
      - "Origin: https://api.puravidabitcoin.io"
      - "Pragma: no-cache"
    body: '{"operationName":"btcPriceList","variables":{"range":"ONE_DAY"},"query":"query btcPriceList($range: PriceGraphRange!) {\\n  btcPriceList(range: $range) {\\n    timestamp\\n    price {\\n      base\\n      offset\\n      currencyUnit\\n      formattedAmount\\n    }\\n  }\\n}\\n"}'

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  # cname: demo.upptime.js.org
  baseUrl: /pura-vida-status
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: PuraVida Application Status
  # introTitle: "**Upptime** is the open-source uptime monitor and status page, powered entirely by GitHub."
  # introMessage: This is a sample status page which uses **real-time** data from our [GitHub repository](https://github.com/upptime/upptime). No server required — just GitHub Actions, Issues, and Pages. [**Get your own for free**](https://github.com/upptime/upptime)
  # navbar:
  #   - title: Status
  #     href: /
  #   - title: GitHub
  #     href: https://github.com/$OWNER/$REPO
# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
