# Change these first
owner: PuraVida-Technologies # Your GitHub organization or username, where this repository lives
repo: pura-vida-status # The name of this repository

sites:
  - name: Pura Vida Website
    url: https://puravidabitcoin.io/
  - name: Pura Vida Pay
    url: https://pay.puravidabitcoin.io/
  - name: Pura Vida Web Wallet
    url: https://wallet.puravidabitcoin.io/
  - name: Pura Vida Merchants
    url: https://merchants.puravidabitcoin.io/
  - name: Pura Vida Market
    url: https://market.puravidabitcoin.io/
  - name: Stablesats
    url: https://aegis.puravidabitcoin.io/health/stablesats
  - name: Bitcoin Node
    url: https://aegis.puravidabitcoin.io/health/bitcoind
  - name: Signer Node
    url: https://aegis.puravidabitcoin.io/health/bitcoind-signer
  - name: Lightning Node
    url: https://aegis.puravidabitcoin.io/health/lnd
  - name: Pura Vida API
    url: https://api.puravidabitcoin.io/graphql
    method: POST
    headers:
      - "Content-Type: application/json"
    body: '{"operationName":"btcPriceList","variables":{"range":"ONE_DAY"},"query":"query btcPriceList($range: PriceGraphRange!) { btcPriceList(range: $range) { timestamp price { base offset currencyUnit formattedAmount } } }"}'
    __dangerous__body_down: "errors"
  - name: Pura Vida API - Exchange Rates
    url: https://api.puravidabitcoin.io/graphql
    method: POST
    headers:
      - "Content-Type: application/json"
    body: '{"operationName": "homeUnauthed", "variables": {"range": "ONE_DAY"}, "query": "query homeUnauthed { globals { network } currencyList { id flag name symbol fractionDigits } }"}'
    __dangerous__body_down: "errors"
  - name: Pura Vida Merchants - Payment Forwarding
    url: https://webhooks.production.pvbtc.cloud/health
  - name: Pura Vida ATMs
    url: https://admin.atm.puravidabitcoin.io/login

# Private Resources; we should transplant these elsewhere.
#  - name: Admin Market - Pura Vida Bitcoin
#    url: https://admin.market.puravidabitcoin.io/
#  - name: Specter - Pura Vida Bitcoin
#    url: https://specter.puravidabitcoin.io/
#  - name: Admin - Pura Vida Bitcoin
#    url: https://admin.puravidabitcoin.io/
#  - name: ArgoCD - Pura Vida Bitcoin
#    url: https://argocd.puravidabitcoin.io/

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  cname: status.puravidabitcoin.io
  #baseUrl: /pura-vida-status
  # logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  theme: light
  logoUrl: https://i0.wp.com/puravidabitcoin.io/wp-content/uploads/2023/03/Logo_H.png
  name: PuraVida Application Status
  # introTitle: "**Upptime** is the open-source uptime monitor and status page, powered entirely by GitHub."
  # introMessage: This is a sample status page which uses **real-time** data from our [GitHub repository](https://github.com/upptime/upptime). No server required — just GitHub Actions, Issues, and Pages. [**Get your own for free**](https://github.com/upptime/upptime)
  # navbar:
  #   - title: Status
  #     href: /
  #   - title: GitHub
  #     href: https://github.com/$OWNER/$REPO
# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
